#数据库连接配置
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://81.69.193.138:3306/mall-ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 81.69.193.138:8848
  application:
    name: mall-member
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.mcl
  global-config:
    db-config:
      id-type: auto #主键自增

server:
  port: 8020
